<?php

use Illuminate\Database\Seeder;

class VesselsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // $vessels = [
        //     'ADEE', 'PORTLINE',
        //     'ADELINE DELMAS', 'CMA/DELMAS',
        //     'ADRIAN', 'CMA/DELMAS',
        //     'AEGEAN PEARL', 'CMA/DELMAS',
        //     'AENNE RICKMERS', 'CMA/DELMAS',
        //     'AFRICA B.', 'BOLLUDA',
        //     'AFRICAN FOREST', 'BOCS',
        //     'AFRICAN RIVER', 'BOCS',
        //     'AFRICAN WIND', 'BOCS',
        //     'AGGELIKI P', 'MSC',
        //     'ALEXANDER', 'MSC',
        //     'ALEXANDER I', 'CMA/DELMAS',
        //     'ALEXANDRA RICKMERS', 'CMA/DELMAS',
        //     'ALGOA BAY', 'MACS',
        //     'ALIOTH', 'CMA/DELMAS',
        //     'ALTONA', 'CMA/DELMAS',
        //     'ANAM CARA III', 'CMA/DELMAS',
        //     'ANDRE RICKMERS', 'CMA/DELMAS',
        //     'ANGOL', 'MSC',
        //     'ANJA', 'CMA/DELMAS',
        //     'ANNABELLE SCHULTE', 'CMA/DELMAS',
        //     'ANTJE WULFF', 'CMA/DELMAS',
        //     'ARELIA', 'CMA/DELMAS',
        //     'ARK FORWADER', 'STENA LINE',
        //     'AROSIA', 'MOL',
        //     'AS ANDULUSIA', 'MOL',
        //     'AS MARS', 'MSC',
        //     'AS POSEIDON', 'MSC',
        //     'ASTOR', 'SCL',
        //     'ATLANTIC CARTIER', 'ACL',
        //     'ATLANTIC COMPANION', 'ACL',
        //     'ATLANTIC COMPASS', 'ACL',
        //     'ATLANTIC CONCERT', 'ACL',
        //     'ATLANTIC CONVEYOR', 'ACL',
        //     'ATLANTIC REEFER', 'ZIM',
        //     'ATLANTIC VOYAGER', 'MOL',
        //     'AZURYT', 'EUROAFRICA',
        //     'BACO LINER 1', 'BACO',
        //     'BACO LINER 2', 'BACO',
        //     'BACO LINER 3', 'BACO',
        //     'BAVARIA', 'CMA/DELMAS',
        //     'BEAUMONT', 'MSC',
        //     'BLACK SEA', 'ZIM',
        //     'BLANDINE DELMAS', 'CMA/DELMAS',
        //     'BOMAR RESILIENT', 'HAPAG-LLOYD',
        //     'BOXFORD', 'CMA/DELMAS',
        //     'BUENOS AIRES', 'CMA/DELMAS',
        //     'BUNGA RAYA DUA', 'MISC',
        //     'BUNGA RAYA SATU', 'MISC',
        //     'BUXFAVORITE', 'ZIM',
        //     'BUXLAGOON', 'MSC',
        //     'BUXLINK', 'MOL',
        //     'BUXSAILOR', 'ZIM',
        //     'BUXSTAR', 'MSC',
        //     'CALAO', 'CMA/DELMAS',
        //     'CALIFORNIA DRAGON', 'MSC',
        //     'CALIFORNIA DRAGON 2R', 'MSC',
        //     'CAP AGULHAS', 'PIL',
        //     'CAP EGMONT', 'CMA/DELMAS',
        //     'CAP EGMONT', 'CMA/DELMAS',
        //     'CAPE HATTERAS', 'CMA/DELMAS',
        //     'CAPE MANILLA', 'MSC',
        //     'CARIBBEAN STAR', 'AFRICA EXPRESS LINE',
        //     'CAROLINA STAR', 'MARGUISA',
        //     'CAROLINE DELMAS', 'CMA/DELMAS',
        //     'CATALINA STAR', 'CMA/DELMAS',
        //     'CEC FUTURE', 'Clipper Project shipping ltd',
        //     'CELINA STAR', 'CMA/DELMAS',
        //     'CENTAURUS', 'CMA/DELMAS',
        //     'CHAITEN', 'MSC',
        //     'CHARLOTTA', 'CMA/DELMAS',
        //     'CHRISTINA I', 'PORTLINE',
        //     'CIELO DI AGADIR', 'MSC',
        //     'CIRCULAR QUAY', 'CMA/DELMAS',
        //     'CITY OF GUANGZHOU', 'ARKAS LINES',
        //     'CITY OF HONG KONG', 'ARKAS LINES',
        //     'CLAES MAERSK', 'ML',
        //     'CLOU OCEAN', 'PORTLINE',
        //     'CMA CGM ACCRA', 'CMA/DELMAS',
        //     'CMA CGM AGUILA', 'CMA/DELMAS',
        //     'CMA CGM AMERICA', 'CMA/DELMAS',
        //     'CMA CGM ANAPURNA', 'CMA/DELMAS',
        //     'CMA CGM AZTECA', 'CMA/DELMAS',
        //     'CMA CGM BRASILIA', 'CMA/DELMAS',
        //     'CMA CGM BUENOS AIRES', 'CMA/DELMAS',
        //     'CMA CGM CAPRICORNE', 'CMA/DELMAS',
        //     'CMA CGM CARIBBEAN', 'CMA/DELMAS',
        //     'CMA CGM COLIBRI', 'CMA/DELMAS',
        //     'CMA CGM COLOMBIE', 'CMA/DELMAS',
        //     'CMA CGM COMOE', 'CMA/DELMAS',
        //     'CMA CGM CORTES', 'CMA/DELMAS',
        //     'CMA CGM ESMERALDA', 'CMA/DELMAS',
        //     'CMA CGM EVEREST', 'CMA/DELMAS',
        //     'CMA CGM IMPALA', 'CMA/DELMAS',
        //     'CMA CGM JAGUAR', 'CMA/DELMAS',
        //     'CMA CGM KAILAS', 'CMA/DELMAS',
        //     'CMA CGM KIWI', 'CMA/DELMAS',
        //     'CMA CGM LA BOUSSOLE', 'CMA/DELMAS',
        //     'CMA CGM LAGOS', 'CMA/DELMAS',
        //     'CMA CGM L''ASTROLABE', 'CMA/DELMAS',
        //     'CMA CGM L''ETOILE', 'CMA/DELMAS',
        //     'CMA CGM LIMON', 'CMA/DELMAS',
        //     'CMA CGM MAYA', 'CMA/DELMAS',
        //     'CMA CGM MONTENEGRO', 'CMA/DELMAS',
        //     'CMA CGM NIGER', 'CMA/DELMAS',
        //     'CMA CGM OKAPI', 'CMA/DELMAS',
        //     'CMA CGM OMAN', 'CMA/DELMAS',
        //     'CMA CGM OUBANGUI', 'CMA/DELMAS',
        //     'CMA CGM PARANA', 'CMA/DELMAS',
        //     'CMA CGM PUMA', 'CMA/DELMAS',
        //     'CMA CGM QUETZAL', 'CMA/DELMAS',
        //     'CMA CGM RABAT', 'CMA/DELMAS',
        //     'CMA CGM RIO GRANDE', 'CMA/DELMAS',
        //     'CMA CGM SAMBHAR', 'CMA/DELMAS',
        //     'CMA CGM SANTOS', 'CMA/DELMAS',
        //     'CMA CGM SIMBA', 'CMA/DELMAS',
        //     'CMA CGM TEMA', 'CMA/DELMAS',
        //     'CMA CGM TOGO', 'CMA/DELMAS',
        //     'CMA CGM VICTORIA', 'CMA/DELMAS',
        //     'CMA CGM VOLTA', 'CMA/DELMAS',
        //     'CMA-CGM BUENOS AIRES', 'CMA/DELMAS',
        //     'COLD STREAM', 'ZIM',
        //     'COLOMBIAN STAR', 'AFRICA EXPRESS LINE',
        //     'COMMANDER', 'CMA/DELMAS',
        //     'COMMODORE', 'NYK',
        //     'CONTI ARABELLA', 'MOL',
        //     'CONTI CARTAGENA', 'ML',
        //     'CONTI CHIWAN', 'MSC',
        //     'CONTI EXPRESS', 'CONTI',
        //     'CONTI SHARJAH', 'MSC',
        //     'CONTI SINGA', 'MSC',
        //     'COSTA RICAN STAR', 'AFRICA EXPRESS LINE',
        //     'COTE DIVOIRIAN STAR', 'AFRICA EXPRESS LINE',
        //     'COTE IVOIRIAN STAR', 'ZIM',
        //     'CRISTINA A.', 'CMA/DELMAS',
        //     'CRISTINA STAR', 'CMA/DELMAS',
        //     'CS DISCOVERY', 'CMA/DELMAS',
        //     'CSAV BRASILIA', 'MSC',
        //     'CSAV CALLAO', 'CSAV',
        //     'CSAV ITAJAI', 'CSAV',
        //     'CSAV MOEMA', 'CSAV',
        //     'CSAV MORUMBI', 'CSAV',
        //     'CSAV NEW YORK', 'CSAV',
        //     'CSAV PARANAGUA', 'CSAV',
        //     'CSAV RAHUE', 'CSAV',
        //     'CSAV RENAICO', 'CSAV',
        //     'CSAV TOTORAL', 'MSC',
        //     'CSAV TRINIDAD', 'CSAV',
        //     'DELMAS BONNY', 'CMA/DELMAS',
        //     'DELMAS BRAZZAVILLE', 'CMA/DELMAS',
        //     'DELMAS KETA', 'CMA/DELMAS',
        //     'DELMAS SEYCHELLES', 'CMA/DELMAS',
        //     'DELPHINE DELMAS', 'CMA/DELMAS',
        //     'DESPINA', 'MSC',
        //     'DIAMOND LAND', 'MACS',
        //     'DIMITRIS C', 'CMA/DELMAS',
        //     'DORIKOS', 'CMA/DELMAS',
        //     'ECLIPSE', 'BOLLUDA',
        //     'EL LOBO', 'SAILS',
        //     'EM CHIOS', 'CMA/DELMAS',
        //     'EM ITHAKI', 'MOL',
        //     'EM KEA', 'CMA/DELMAS',
        //     'EM PSARA', 'CMA/DELMAS',
        //     'EMERALD', 'EUROAFRICA',
        //     'EMILIA', 'SAILS',
        //     'ESPERANZA N', 'MOL',
        //     'EUROCARGO AFRICA', 'GRIMALDI',
        //     'EUROCARGO BARI', 'GRIMALDI',
        //     'EUROCARGO EUROPA', 'GRIMALDI',
        //     'EUROCARGO ISTAMBUL', 'GRIMALDI',
        //     'EUROCARGO SALERNO', 'GRIMALDI',
        //     'FESCO ASKOLD', 'MSC',
        //     'FRANCISCA SCHULTE', 'CMA/DELMAS',
        //     'FRIJSENBORG', 'NORDANA',
        //     'FRISIA HANNOVER', 'MOL',
        //     'FRISIA HELSINKI', 'MOL',
        //     'FRISIA LUBECK', 'MOL',
        //     'FRISIA ROSTOCK', 'MOL',
        //     'GARNET ACE', 'MOL',
        //     'GEORG SCHULTE', 'CMA/DELMAS',
        //     'GERD', 'MSC',
        //     'GISELE A', 'ARKAS LINES',
        //     'GOLDEN ISLE', 'MACS',
        //     'GRANAT', 'EUROAFRICA',
        //     'GRAND VISION', 'MSC',
        //     'GRANDE AFRICA', 'GRIMALDI',
        //     'GRANDE AMBURGO', 'GRIMALDI',
        //     'GRANDE AMERICA', 'GRIMALDI',
        //     'GRANDE ANGOLA', 'GRIMALDI',
        //     'GRANDE ARGENTINA', 'GRIMALDI',
        //     'GRANDE ATLANTICO', 'GRIMALDI',
        //     'GRANDE BENIN', 'GRIMALDI',
        //     'GRANDE BRASILE', 'GRIMALDI',
        //     'GRANDE BUENOS AIRES', 'GRIMALDI',
        //     'GRANDE C. D''AVORIO', 'GRIMALDI',
        //     'GRANDE CAMEROON', 'GRIMALDI',
        //     'GRANDE CONGO', 'GRIMALDI',
        //     'GRANDE COSTA', 'GRIMALDI',
        //     'GRANDE COSTA D AVORI', 'GRIMALDI',
        //     'GRANDE COSTA D''AVORIO', 'GRIMALDI',
        //     'GRANDE FRANCIA', 'GRIMALDI',
        //     'GRANDE GABON', 'GRIMALDI',
        //     'GRANDE GHANA', 'GRIMALDI',
        //     'GRANDE GUINEA', 'GRIMALDI',
        //     'GRANDE LAGOS', 'GRIMALDI',
        //     'GRANDE MAROCCO', 'GRIMALDI',
        //     'GRANDE MOROCCO', 'GRIMALDI',
        //     'GRANDE NIGERIA', 'GRIMALDI',
        //     'GRANDE SAN PAOLO', 'GRIMALDI',
        //     'GRANDE SENEGAL', 'GRIMALDI',
        //     'GRANDE SIERRA LEONE', 'GRIMALDI',
        //     'GRANDE TOGO', 'GRIMALDI',
        //     'GREEN CAPE', 'MACS',
        //     'GULBENIZ A', 'ARKAS LINES',
        //     'GUSTAV SCHULTE', 'CMA/DELMAS',
        //     'HAMMONIA PACIFICUM', 'NYK',
        //     'HANNES C.', 'PORTLINE',
        //     'HANSA CATALINA', 'CMA/DELMAS',
        //     'HANSA CENTURION', 'CMA/DELMAS',
        //     'HANSA CLOPPENBURG', 'HAPAG-LLOYD',
        //     'HANSA FREYBURG', 'CMA/DELMAS',
        //     'HANSA LIMBURG', 'HAPAG-LLOYD',
        //     'HANSA MARBURG', 'HAPAG-LLOYD',
        //     'HANSA NARVIK', 'CMA/DELMAS',
        //     'HANSA RIGA', 'CMA/DELMAS',
        //     'HANSA VICTORY', 'CMA/DELMAS',
        //     'HEBE', 'MSC',
        //     'HELENE J', 'MESSINA',
        //     'HELENE RUSS', 'CMA/DELMAS',
        //     'HELLE RITSCHER', 'CMA/DELMAS',
        //     'HELMUT', 'MSC',
        //     'HERMANN HESSE', 'MOL',
        //     'HISPANIA', 'PORTLINE',
        //     'HOPE', 'MSC',
        //     'HS BERLIOZ', 'CMA/DELMAS',
        //     'HS CHOPIN', 'CMA/DELMAS',
        //     'HS DISCOVERER', 'CMA/DELMAS',
        //     'HS LIVINGSTONE', 'MSC',
        //     'HS SCOOT', 'MSC',
        //     'ISABELLE SCHULTE', 'CMA/DELMAS',
        //     'ISOLDE', 'CMA/DELMAS',
        //     'IWASHIRO', 'PIL',
        //     'JANA', 'MSC',
        //     'JOLLY ARGENTO', 'MESSINA',
        //     'JOLLY BIANCO', 'MESSINA',
        //     'JOLLY CORALLO', 'MESSINA',
        //     'JOLLY MARONE', 'MESSINA',
        //     'JOLLY ROSSO', 'MESSINA',
        //     'JOLLY VERDE', 'MESSINA',
        //     'JOLLY ZAFFIRO', 'MESSINA',
        //     'JONNI RITSCHER', 'CMA/DELMAS',
        //     'JPO GEMINI', 'ML',
        //     'JULIA SCHULTE', 'ML',
        //     'JULIE DELMAS', 'CMA/DELMAS',
        //     'KARIN S', 'CMA/DELMAS',
        //     'KEMAL A', 'ARKAS LINES',
        //     'KERSTIN S', 'ML',
        //     'KING JUSTUS', 'MSC',
        //     'KLAUS J', 'MESSINA',
        //     'KOLLMAR', 'MESSINA',
        //     'KOMODO', 'MSC',
        //     'KONRAD SCHULTE', 'HAPAG-LLOYD',
        //     'KOTA AKBAR', 'PIL',
        //     'KOTA ANGGERIK', 'PIL',
        //     'KOTA ANGGUN', 'PIL',
        //     'KOTA ARIF', 'PIL',
        //     'KOTA AZAM', 'PIL',
        //     'KOTA BAHAGIA', 'PIL',
        //     'KOTA BERANI', 'PIL',
        //     'KOTA BERJAYA', 'PIL',
        //     'KOTA BERKAT', 'PIL',
        //     'KOTA BERLIAN', 'PIL',
        //     'KOTA HAKIM', 'PIL',
        //     'KOTA HALUS', 'PIL',
        //     'KOTA HANDAL', 'PIL',
        //     'KOTA HAPAS', 'PIL',
        //     'KOTA HARUM', 'PIL',
        //     'KOTA HENING', 'PIL',
        //     'KOTA KAMIL', 'PIL',
        //     'KOTA KARIM', 'PIL',
        //     'KOTA KAYA', 'PIL',
        //     'KOTA MANIS', 'PIL',
        //     'KOTA MAWAR', 'PIL',
        //     'KOTA MESRA', 'PIL',
        //     'KOTA SABAS', 'PIL',
        //     'L', '',
        //     'LADY ROSE', 'AFRICA EXPRESS LINE',
        //     'LADY ROSEBAY', 'AFRICA EXPRESS LINE',
        //     'LADY ROSEBUD', 'AFRICA EXPRESS LINE',
        //     'LADY ROSEMARY', 'AFRICA EXPRESS LINE',
        //     'LAURA DELMAS', 'CMA/DELMAS',
        //     'LAURA MAERSK', 'ML',
        //     'LAUST MAERSK', 'ML',
        //     'LEDA MAERSK', 'ML',
        //     'LEDA TRADER', 'MSC',
        //     'LEXA MAERSK', 'ML',
        //     'LICA MAERSK', 'ML',
        //     'LIRCAY', 'CSAV',
        //     'LONDON TOWER', 'PIL',
        //     'LOUISA SCHULTE', 'MESSINA',
        //     'LUCIE DELMAS', 'CMA/DELMAS',
        //     'LUNA MAERSK', 'ML',
        //     'MACAO STRAIT', 'CMA/DELMAS',
        //     'MACUBA', 'SCL',
        //     'MAERSK NEUSTADT', 'ML',
        //     'MAERSK WILMINGTON', 'ML',
        //     'MAERSK WINDHOEK', 'ML',
        //     'MAESTRO OCEAN', 'CMA/DELMAS',
        //     'MAESTRO SEA', 'CMA/DELMAS',
        //     'MAESTRO SUN', 'CMA/DELMAS',
        //     'MAESTRO UNIVERSE', 'CMA/DELMAS',
        //     'MALACHIT', 'EUROAFRICA',
        //     'MANX LION', 'PORTLINE',
        //     'MARE CARIBICUM', 'MSC',
        //     'MARGARETE SCHULTE', 'CMA/DELMAS',
        //     'MARIE DELMAS', 'CMA/DELMAS',
        //     'MARIENBORG', 'NORDANA',
        //     'MARINA', 'CMA/DELMAS',
        //     'MARIO A.', 'ML',
        //     'MARIVIA', 'CMA/DELMAS',
        //     'MARMARA SEA', 'ZIM',
        //     'MARUBA CRISTINA', 'MARUBA',
        //     'MATE', 'NYK',
        //     'MAULE', 'MSC',
        //     'MAXINE', 'MSC',
        //     'MCP VIENNA', 'MSC',
        //     'MCS AMERICA', 'MSC',
        //     'MERCHANT', 'MSC',
        //     'MERKUR', 'CMA/DELMAS',
        //     'MERKUR BAY', 'NYK',
        //     'MICHAELA S.', 'ML',
        //     'MICHEL A.', 'SCL',
        //     'MISC DARLINGTON', 'MISC',
        //     'MN CALAO', 'CMA/DELMAS',
        //     'MOL', 'MOL',
        //     'MOL HONOR', 'MOL',
        //     'MOL SASSANDRA', 'MOL',
        //     'MOL SEABREEZE', 'MOL',
        //     'MOL STABILITY', 'MOL',
        //     'MOL SYMPHONY', 'MOL',
        //     'MOL VALPARAISO', 'MOL',
        //     'MOL VOLTA', 'MOL',
        //     'MSC ACCRA', 'MSC',
        //     'MSC ADRIATIC', 'MSC',
        //     'MSC AFRICA', 'MSC',
        //     'MSC AGATA', 'MSC',
        //     'MSC ALABAMA', 'MSC',
        //     'MSC ALEXA', 'MSC',
        //     'MSC ALEXANDRA', 'MSC',
        //     'MSC ALEXANDRA', 'MSC',
        //     'MSC ALICANTE', 'MSC',
        //     'MSC AMERICA', 'MSC',
        //     'MSC AMSTERDAM', 'MSC',
        //     'MSC ASTRID', 'MSC',
        //     'MSC ATLANTIC', 'MSC',
        //     'MSC BARBARA', 'MSC',
        //     'MSC BENEDETTA', 'MSC',
        //     'MSC BORNEO', 'MSC',
        //     'MSC BREMEN', 'MSC',
        //     'MSC BROOKE', 'MSC',
        //     'MSC BULGARIA', 'MSC',
        //     'MSC CANBERRA', 'MSC',
        //     'MSC CATANIA', 'MSC',
        //     'MSC CHANECA', 'MSC',
        //     'MSC CHIARA', 'MSC',
        //     'MSC CONFIDENCE', 'MSC',
        //     'MSC CORINNA', 'MSC',
        //     'MSC DENISSE', 'MSC',
        //     'MSC DIDEM', 'MSC',
        //     'MSC DON GIOVANNI', 'MSC',
        //     'MSC DONATA', 'MSC',
        //     'MSC DYMPHNA', 'MSC',
        //     'MSC ELA', 'MSC',
        //     'MSC ELENI', 'MSC',
        //     'MSC ELEONORA', 'MSC',
        //     'MSC ELOISE', 'MSC',
        //     'MSC EMIHRAN', 'MSC',
        //     'MSC EMMA', 'MSC',
        //     'MSC ENGLAND', 'MSC',
        //     'MSC EUGENIA', 'MSC',
        //     'MSC FABIENNE', 'MSC',
        //     'MSC FEDERICA', 'MSC',
        //     'MSC FINLAND', 'MSC',
        //     'MSC FLAMINIA', 'MSC',
        //     'MSC FLORIANA', 'MSC',
        //     'MSC GABRIELLA', 'MSC',
        //     'MSC GINA', 'MSC',
        //     'MSC GRACE', 'MSC',
        //     'MSC HAILEY', 'MSC',
        //     'MSC HARMONY', 'MSC',
        //     'MSC HIMALAYA', 'MSC',
        //     'MSC INDIA', 'MSC',
        //     'MSC ISABELLE', 'MSC',
        //     'MSC ISHYKA', 'MSC',
        //     'MSC ITEA', 'MSC',
        //     'MSC JADE', 'MSC',
        //     'MSC JAPAN', 'MSC',
        //     'MSC JASMINE', 'MSC',
        //     'MSC JENNY', 'MSC',
        //     'MSC JILHAN', 'MSC',
        //     'MSC JORDAN', 'MSC',
        //     'MSC KERRY', 'MSC',
        //     'MSC KOREA', 'MSC',
        //     'MSC LARA', 'MSC',
        //     'MSC LAURA', 'MSC',
        //     'MSC LAUREN', 'MSC',
        //     'MSC LAURENCE', 'MSC',
        //     'MSC LAUSANNE', 'MSC',
        //     'MSC LEA', 'MSC',
        //     'MSC LEILA', 'MSC',
        //     'MSC LEVINA', 'MSC',
        //     'MSC LISBON', 'MSC',
        //     'MSC LONDON', 'MSC',
        //     'MSC LONGONI', 'MSC',
        //     'MSC LORENA', 'MSC',
        //     'MSC LORETTA', 'MSC',
        //     'MSC LUCIA', 'MSC',
        //     'MSC LUGANO', 'MSC',
        //     'MSC LUISA', 'MSC',
        //     'MSC MAHIMA', 'MSC',
        //     'MSC MANDY', 'MSC',
        //     'MSC MARA', 'MSC',
        //     'MSC MARIA LAURA', 'MSC',
        //     'MSC MARIANNA', 'MSC',
        //     'MSC MARTINA', 'MSC',
        //     'MSC MASCARET', 'MSC',
        //     'MSC MATILDE', 'MSC',
        //     'MSC MAUREEN', 'MSC',
        //     'MSC MAYA', 'MSC',
        //     'MSC MEDITERRANEAN', 'MSC',
        //     'MSC MESSINA', 'MSC',
        //     'MSC METHONI', 'MSC',
        //     'MSC MICHAELA', 'MSC',
        //     'MSC MIRELLA', 'MSC',
        //     'MSC MONICA', 'MSC',
        //     'MSC NAMIBIA', 'MSC',
        //     'MSC NATALIA', 'MSC',
        //     'MSC NEDERLAND', 'MSC',
        //     'MSC NOA', 'MSC',
        //     'MSC NORMANDIE', 'MSC',
        //     'MSC OLGA', 'MSC',
        //     'MSC PANAMA', 'MSC',
        //     'MSC PAOLA', 'MSC',
        //     'MSC PAOLO', 'MSC',
        //     'MSC PATRICIA', 'MSC',
        //     'MSC PILAR', 'MSC',
        //     'MSC PRAGUE', 'MSC',
        //     'MSC RAFAELA', 'MSC',
        //     'MSC REBECCA', 'MSC',
        //     'MSC REGINA', 'MSC',
        //     'MSC RITA', 'MSC',
        //     'MSC RONIT', 'MSC',
        //     'MSC ROSSELLA', 'MSC',
        //     'MSC SABRINA', 'MSC',
        //     'MSC SAMANTHA', 'MSC',
        //     'MSC SANDRA', 'MSC',
        //     'MSC SANTHYA', 'MSC',
        //     'MSC SCOTLAND', 'MSC',
        //     'MSC SELIN', 'MSC',
        //     'MSC SERENA', 'MSC',
        //     'MSC SHANNON', 'MSC',
        //     'MSC SHARJAH', 'MSC',
        //     'MSC SHIRLEY', 'MSC',
        //     'MSC SIERRA II', 'MSC',
        //     'MSC SONIA', 'MSC',
        //     'MSC SOPHIE', 'MSC',
        //     'MSC STEFANIA', 'MSC',
        //     'MSC STELLA', 'MSC',
        //     'MSC SUDAN', 'MSC',
        //     'MSC SUEZ', 'MSC',
        //     'MSC TOBA', 'MSC',
        //     'MSC UKRAINE', 'MSC',
        //     'MSC ULSAN', 'MSC',
        //     'MSC VALERIA', 'MSC',
        //     'MSC VANESSA', 'MSC',
        //     'MSC VERONIQUE', 'MSC',
        //     'MSC VIENNA', 'MSC',
        //     'MSC VOLTA', 'MSC',
        //     'MSC VOYAGER', 'MSC',
        //     'MSC WASHINGTON', 'MSC',
        //     'MSC ZANZIBAR', 'MSC',
        //     'MSC ZURICH', 'MSC',
        //     'NAIROBI', 'MSC',
        //     'NATALIE SCHULTE', 'CMA/DELMAS',
        //     'NEDLLOYD EVITA', 'ML',
        //     'NEDLLOYD TESLIN', 'ML',
        //     'NEFRYT', 'EUROAFRICA',
        //     'NEPTUN', 'CMA/DELMAS',
        //     'NICOLAS DELMAS', 'CMA/DELMAS',
        //     'NIKOLAS', 'MSC',
        //     'NORDRIVER', 'CMA/DELMAS',
        //     'NORDSTRAND', 'CSAV',
        //     'NORTHERN DEBONAIR', 'MSC',
        //     'NORTHERN HAPPINESS', 'CMA/DELMAS',
        //     'NOVIA', 'CMA/DELMAS',
        //     'NYK ESTRELA', 'NYK',
        //     'NYK FLORESTA', 'NYK',
        //     'OCEAN PROTECTOR', 'MSC',
        //     'OLIVIA', 'CMA/DELMAS',
        //     'ONYX', 'EUROAFRICA',
        //     'ORINOCO RIVER', 'SAILS',
        //     'OXL LOTUS', 'BOLLUDA',
        //     'PACIFIC EXPRESS', 'CONTI',
        //     'PARIS', 'PIL',
        //     'PATRICIA SCHULTE', 'CMA/DELMAS',
        //     'PCE MADEIRA', 'ML',
        //     'PEARL RIVER', 'MSC',
        //     'PELICAN', 'BOLLUDA',
        //     'PENELOPE', 'CMA/DELMAS',
        //     'PETKUM', 'CMA/DELMAS',
        //     'PLUTO', 'CMA/DELMAS',
        //     'POLARIS', 'MSC',
        //     'PORT TEJO', 'PORTLINE',
        //     'PORTOFINO', 'GRIMALDI',
        //     'PRAIA', 'CMA/DELMAS',
        //     'PRIMAVERA', 'MSC',
        //     'PRIMUS', 'CMA/DELMAS',
        //     'PRIWALL', 'MSC',
        //     'PUCON', 'MSC',
        //     'QUEEN OF LUCK', 'CMA/DELMAS',
        //     'R. R. AMERICA', 'CMA/DELMAS',
        //     'R; SEA', 'CMA/DELMAS',
        //     'REGAL STAR', 'ZIM',
        //     'REPUBBLICA ARGENTINA', 'GRIMALDI',
        //     'REPUBBLICA DEL BRASILE', 'GRIMALDI',
        //     'REPUBBLICA DI AMALFI', 'GRIMALDI',
        //     'REPUBBLICA DI ROMA', 'GRIMALDI',
        //     'REPUBBLICA DI VENEZIA', 'GRIMALDI',
        //     'RHL AQUA', 'CMA/DELMAS',
        //     'RHLAQUA', 'CMA/DELMAS',
        //     'RIO DE JANEIRO', 'MSC',
        //     'RIO TESLIN', 'CMA/DELMAS',
        //     'RIO THOMPSON', 'CMA/DELMAS',
        //     'ROSA DELMAS', 'CMA/DELMAS',
        //     'ROSBORG', 'NORDANA',
        //     'ROTORUA', 'HAPAG-LLOYD',
        //     'SAFMARINE PANTANAL', 'SCL',
        //     'SAFMARINE SALOUM', 'SCL',
        //     'SAFMARINE SANAGA', 'SCL',
        //     'SAG WESTFALEN', 'CMA/DELMAS',
        //     'SAN FELIPE', 'CMA/DELMAS',
        //     'SAN FERNANDO', 'CMA/DELMAS',
        //     'SAN FRANCISCO', 'CMA/DELMAS',
        //     'SANTA GIORGINA', 'MOL',
        //     'SANTA MADDALENA', 'CSAV',
        //     'SANTA MONICA', 'MSC',
        //     'SANTA MONICA', 'MSC',
        //     'SAWASDEE HONGKONG', 'CMA/DELMAS',
        //     'SAWASDEE JAKARTA', 'CMA/DELMAS',
        //     'SCL BERN', 'Swiss Cargo Line',
        //     'SCT CHILE', 'MSC',
        //     'SEA BREEZE', 'GRIMALDI',
        //     'Select Vessel Name', 'Operator',
        //     'SHANTI', 'ML',
        //     'SIMA SINGAPORE', 'MSC',
        //     'SLOMAN PRODUCER', 'BOLLUDA',
        //     'SPERO', 'CMA/DELMAS',
        //     'SPIRIT OF CAPETOWN', 'CMA/DELMAS',
        //     'STADT SCHWERIN', 'SCL',
        //     'STAR SERVICE', 'ZIM',
        //     'STAR STANDARD', 'ZIM',
        //     'STAR TRUST', 'ZIM',
        //     'START FIRST', 'ZIM',
        //     'STELLENBOSCH', 'MACS',
        //     'STRAUSS', 'CMA/DELMAS',
        //     'SURINAM RIVER', 'SCL',
        //     'SZAFIR', 'EUROAFRICA',
        //     'TAGA BAY', 'SAILS',
        //     'TAMPA BAY', 'CSAV',
        //     'TASMANIA', 'MSC',
        //     'TERRA BONA', 'PIL',
        //     'TERRA LUMINA', 'PIL',
        //     'TERRY DOS', 'CABOMUNDO',
        //     'TERRY SIETE', 'CABOMUNDO',
        //     'TERRY TRES', 'CABOMUNDO',
        //     'THASOS', 'MSC',
        //     'THEBELAND', 'GRIMALDI',
        //     'THORSWAVE', 'ZIM',
        //     'THURÖ MAERSK', 'ML',
        //     'TOKATA', 'MSC',
        //     'TRAVE TRADER', 'CMA/DELMAS',
        //     'TROENSE MAERSK', 'ML',
        //     'TROYBURG', 'PIL',
        //     'TYRUSLAND', 'GRIMALDI',
        //     'ULYSSES', 'MOL',
        //     'URANUS', 'CMA/DELMAS',
        //     'UTE OLTMANN', 'MSC',
        //     'VAAL RIVER', 'SAILS',
        //     'VERO B', 'BOLLUDA',
        //     'VERO B.', 'BOLLUDA',
        //     'VIOLET', 'CMA/DELMAS',
        //     'VIRANA', 'CMA/DELMAS',
        //     'VITALITY', 'CMA/DELMAS',
        //     'WEC GOYA', 'MSC',
        //     'WEC SOROLLA', 'MSC',
        //     'WEC VELAZQUEZ', 'MSC',
        //     'WEDELLSBORG', 'NORDANA',
        //     'WEHR ALSTER', 'ARKAS LINES',
        //     'WEHR ELBE', 'MOL',
        //     'WEHR HAVEL', 'ARKAS LINES',
        //     'WEHR OSTE', 'CMA/DELMAS',
        //     'WEHR WESER', 'CMA/DELMAS',
        //     'WESTERHAMM', 'MSC',
        //     'WESTERMOOR', 'CMA/DELMAS',
        //     'WESTERTAL', 'MSC',
        //     'WILD LOTUS', 'MOL',
        //     'YK SASSANDRA', 'MOL',
        //     'ZAGORA', 'MSC',
        //     'ZERAN', 'CMA/DELMAS',
        //     'MSC GIORGIA', 'MSC',
        //     'CMA CGM MEKNES', 'CMA/DELMAS',
        //     'GULBENIZ A', 'ZIM',
        //     'MONA LISA', 'MSC',
        //     'HANSE RELIANCE', 'CMA/DELMAS',
        //     'PARTICI', 'CMA/DELMAS',
        //     'CMA CGM MEKNES', 'CMA/DELMAS',
        //     'DELMAS SWALA', 'CMA/DELMAS',
        //     'SCL ANGELA', 'Swiss Cargo Line',
        //     'ORIENT SPIRIT', 'ACL',
        //     'GRANDE TEMA', 'GRIMALDI',
        //     'ATLANTIC NAVIGATOR', 'CSAL',
        //     'SONOMA', 'MESSINA',
        //     'MSC BANU', 'MSC',
        //     'CALISTO', 'CMA/DELMAS',
        //     'LUDWIG SCHULTE', 'HAPAG-LLOYD',
        //     'NIMET', 'BOLLUDA',
        //     'GRANDE COTONOU', 'GRIMALDI',
        //     'HOEGH TRANSPORTER', 'HOEGH AUTOLINERS',
        //     'GRANDE SANTHYA', 'GRIMALDI',
        //     'THORCO HILDE', 'THORCO SHIPPING',
        //     'JSP LEVANTE', 'CMA/DELMAS',
        //     'MILAN TRADER', 'MESSINA',
        //     'PACIFIC REEFER', 'ZIM',
        //     'NOMADIC MILDE', 'NOMADIC',
        //     'ATHENA', 'MSC',
        //     'ELBINSEL', 'CMA/DELMAS',
        //     'ISODORA', 'ARKAS LINES',
        //     'PETALIDI', 'CMA/DELMAS',
        //     'MOEN ISLAND', 'HAPAG-LLOYD',
        //     'DURANDE', 'HAPAG-LLOYD',
        //     'MSC NAMIBIA II', 'MSC',
        //     'GRANDE ABIDJAN', 'GRIMALDI',
        //     'GRANDE LUANDA', 'GRIMALDI',
        //     'CMA CGM AFRICA ONE', 'CMA/DELMAS',
        //     'ALTINIA', 'MNM AFRICAN SHIPPING',
        //     'TANGARA', 'ZIM',
        //     'CMA CGM AFRICA FOUR', 'CMA/DELMAS',
        //     'HOEGH TROOPER', 'HOEGH AUTOLINERS',
        //     'MV MARTIN', 'HAPAG-LLOYD',
        //     'VIVIEN A', 'HAPAG-LLOYD',
        //     'LIBERTY ACE', 'ZIM',
        //     'MERITIUS', 'ZIM',
        //     'CMA CGM AFRICA TWO', 'CMA/DELMAS',
        //     'THORCO AURORA', 'THORCO SHIPPING	',
        //     'PAGNA', 'ZIM',
        //     'CMA CGM AFRICA THREE', 'CMA/DELMAS',
        //     'LIEKE', 'NOORDRIVER SHIPPING',
        //     'MORNING LUCY', 'EUKOR',
        //     'CARY RICKMERS', 'RICKMERS GROUP',
        //     'SEBRING EXPRESS', 'SALLAUM LINES',
        //     'GLOVIS CROWN', 'HYUNDAI GLOVIS',
        //     'M/V SPAR SPICA', 'SPAR SHIPPING',
        //     'GLOVIS SUMMIT', 'HYUNDAI GLOVIS',
        //     'ESL EUROPA', 'ZIM',
        //     'SILVER SKY', 'SALLAUM LINES',
        //     'ALLIANCE NORFOLK', 'ALLIANCE NAVIGATION',
        //     'BALTIC MERCUR II', 'ATLANTIC RO-RO CARRIERS',
        //     'MURORAN', 'BREADBOX SHIPPING LINES',
        //     'WANDA A', 'HAPAG-LLOYD',
        //     'MSC ANIELLO', 'MSC',
        //     'VIKING EAGLE', 'HAPAG-LLOYD',
        //     'LEONIE P', 'BOLLUDA',
        //     'WAF PASSION', 'BOCS',
        //     'CORSICA LINEA DUI', 'CORSICA LINEA',
        //     'TIP HELSINKI', 'CARISBROOKE SHIPPING',
        //     'CMA CGM AGADIR', 'CMA/DELMAS',
        //     'THOR COMMANDER', 'THORCO SHIPPING	',
        //     'TRADE NAVIGATOR', 'FORESTWAVE NAVIGATION',
        //     'MV TASMAN MERMAID', 'HAPAG-LLOYD',
        //     'FRISIA KIEL', 'ZIM',
        //     'HOHEPLATE', 'CMA/DELMAS',
        //     'CORCOVADO', 'ARKAS LINES',
        //     'KATHARINAS', 'CMA/DELMAS',
        //     'BALTIC PATRIOT', 'BALTIC REEFERS',
        //     'MATAR N', 'CMA/DELMAS',
        //     'YANKI A', 'ARKAS LINES',
        //     'THORCO ROYAL', 'THORCO SHIPPING	',
        //     'REPULSE BAY', 'ZIM',
        //     'DEVON STRAIT', 'CMA/DELMAS',
        //     'VIRGINIA TRADER', 'LOMAR SHIPPING',
        //     'MAX WINNER', 'ZIM',
        //     'MSC DIEGO', 'MSC',
        //     'LAYLA', 'ZIM',
        //     'SEATRADE ORANGE', 'ZIM',
        //     'MORNING CHAMPION', 'EUKOR',
        //     'MSC JOY', 'MSC',
        //     'THORCO ARCTIC', 'THORCO SHIPPING	',
        //     'AS PALATIA', 'MESSINA',
        //     'MSC SHAULA', 'MSC',
        //     'MSC MONTEREY', 'MSC',
        //     'MSC LEIGH', 'MSC',
        //     'MSC CARMEN', 'MSC',
        //     'BBC MARMARA', 'BRIESE SHIPPING',
        //     'TIM-S', 'MSC',
        //     'CORSAIR', 'ZIM',
        //     'ADELHEID-S', 'MSC',
        //     'SAN FERNANDO REY', 'TSCHUDI SHIPPING',
        //     'MV FRIA', 'CAFISERVICE SPA',
        //     'MSC KATYAYNI', 'MSC',
        //     'OREGON TRADER', 'HAPAG-LLOYD',
        //     'HOEGH COPENHAGEN', 'HOEGH AUTOLINERS',
        //     'MV THORCO CRYSTAL', 'THORCO SHIPPING	',
        //     'THORCO LEGION', 'THORCO SHIPPING	',
        //     'MSC ANAHITA', 'MSC',
        //     'HOHEWEG', 'BOLLUDA',
        //     'FRANCOISE GILOT', 'CMA/DELMAS',
        //     'GRANDE DAKAR', 'GRIMALDI',
        //     'IRENES REMEDY', 'HAPAG-LLOYD',
        //     'FRISIA OSLO', 'HAPAG-LLOYD',
        //     'ABIDJAN EXPRESS', 'HAPAG-LLOYD',
        //     'HANSA RENDSBURG', 'HAPAG-LLOYD',
        //     'GALA TRIO', 'TRIO SHIPPING',
        //     'ASIATIC LIBERTY', 'ASIATIC LLOYD',
        //     'FLEUR N', 'CMA/DELMAS',
        //     'V ARCTIC TERN', 'TBS SHIPPING SERVICES',
        //     'THORCO MANATEE', 'THORCO SHIPPING	',
        //     'RHL AUDACIA', 'CMA/DELMAS',
        //     'MSC ROSARIA', 'MSC',
        //     'KENT TRADER', 'LOMAR SHIPPING',
        //     'BUXTEHUDE', 'MSC',
        //     'MAX WONDER', 'CMA/DELMAS',
        //     'MSC ANGELA', 'MSC',
        //     'SONGA ANTOFAGASTA', 'MSC',
        //     'SONGA ALYA', 'MSC',
        //     'MSC KORONI', 'MSC',
        //     'CALAIS TRADER', 'MESSINA',
        //     'PARIS JR', 'MSC',
        //     'AS CARELIA', 'HAPAG-LLOYD',
        //     'IRENES RAINBOW', 'MESSINA',
        //     'MIMMI SCHULTE', 'AFRICA EXPRESS LINE',
        //     'THORCO GLORY', 'THORCO SHIPPING	',
        //     'SEASPAN JAKARTA', 'CMA/DELMAS',
        //     'MSC CORUNA', 'MSC',
        //     'CAPE MANILA', 'MSC',
        //     'MSC VIGO', 'MSC',
        //     'HARMONY N', 'HAPAG-LLOYD',
        //     'SOLSTICE N', 'MSC',
        //     'FENG HUANG SONG', 'COSCO',
        //     'MANOLIS P', 'MSC',
        //     'DENIZHAN BAYRAKTAR', 'BOLLUDA',
        //     'MSC CAROLINA', 'MSC',
        //     'NOTHERN DEBONAIR', 'MSC',
        //     'PANTHERA J', 'ARKON SHIPPING',
        //     'INGA A', 'ARKAS LINES',
        //     'CMA CGM LAPIS', 'CMA/DELMAS',
        //     'MSC JEMIMA', 'MSC',
        //     'CMA CGM PLATON', 'CMA/DELMAS',
        //     'CMA CGM HOMERE', 'CMA/DELMAS',
        //     'LUTETIA', 'CMA/DELMAS',
        //     'KARSNES', 'KLIP MARINE',
        //     'ARICA', 'HAPAG-LLOYD',
        //     'NORTHERN DECISION', 'MSC',
        //     'CHOPIN', 'MARGUISA',
        //     'MARTHA SCHULTE', 'CMA/DELMAS',
        //     'LOUIS S', 'CMA/DELMAS',
        //     'PORT GDYNIA', 'CMA/DELMAS',
        //     'LILLY SCHULTE', 'CMA/DELMAS',
        //     'CMA CGM ARISTOTE', 'CMA/DELMAS',
        //     'VIKING MERLIN', 'HAPAG-LLOYD',
        //     'LETO', 'CMA/DELMAS',
        //     'E.R. FRANCE', 'MSC',
        //     'MAPLE LEA', 'THORCO SHIPPING',
        //     'BREADBOX  FALCON', 'BREADBOX SHIPPING LINES',
        //     'YM ANTWERP', 'MSC',
        //     'COSTA RICA STAR', 'AFRICA EXPRESS LINE',
        //     'ATLANTIC WEST', 'CMA/DELMAS',
        //     'ATLANTIC DAWN', 'BALTIC SHIPPING',
        //     'MV TUNGOR', 'SEACO',
        //     'POCAHONTAS', 'CMA/DELMAS',
        //     'MSC COBALTO', 'MSC',
        //     'ATLANTIC DISCOVERER', 'CMA/DELMAS',
        //     'NEONILA', 'BOLLUDA',
        //     'LEADER CANAKKALE', 'MILLER AND FLAMA SHIPPING',
        //     'MSC MADRID', 'MSC',
        //     'MSC JANIS 3', 'MSC',
        //     'NORDMAPLE', 'CMA/DELMAS',
        //     'EM ATHENS', 'CMA/DELMAS',
        //     'OKEE ANN MARI', 'HAPAG-LLOYD',
        //     'CS SETUBAL', 'MSC',
        //     'THORCO RIO', 'THORCO SHIPPING',
        //     'AS SELINA', 'HAPAG-LLOYD',
        //     'HANSA ASIA', 'MSC',
        //     'HOEGH TARGET', 'HOEGH AUTOLINERS',

        // ]
    }
}
