<?php

namespace App\Http\Controllers;

use App\Shipping;
use App\Vesselle;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

class DataController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $vessels = [
            ['vessel' => 'ADEE', 'shippingLine' =>  'PORTLINE',],
            ['vessel' => 'ADELINE DELMAS', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'ADRIAN', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'AEGEAN PEARL', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'AENNE RICKMERS', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'AFRICA B.', 'shippingLine' =>  'BOLLUDA',],
            ['vessel' => 'AFRICAN FOREST', 'shippingLine' =>  'BOCS',],
            ['vessel' => 'AFRICAN RIVER', 'shippingLine' =>  'BOCS',],
            ['vessel' => 'AFRICAN WIND', 'shippingLine' =>  'BOCS',],
            ['vessel' => 'AGGELIKI P', 'shippingLine' =>  'MSC',],
            ['vessel' => 'ALEXANDER', 'shippingLine' =>  'MSC',],
            ['vessel' => 'ALEXANDER I', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'ALEXANDRA RICKMERS', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'ALGOA BAY', 'shippingLine' =>  'MACS',],
            ['vessel' => 'ALIOTH', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'ALTONA', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'ANAM CARA III', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'ANDRE RICKMERS', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'ANGOL', 'shippingLine' =>  'MSC',],
            ['vessel' => 'ANJA', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'ANNABELLE SCHULTE', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'ANTJE WULFF', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'ARELIA', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'ARK FORWADER', 'shippingLine' =>  'STENA LINE',],
            ['vessel' => 'AROSIA', 'shippingLine' =>  'MOL',],
            ['vessel' => 'AS ANDULUSIA', 'shippingLine' =>  'MOL',],
            ['vessel' => 'AS MARS', 'shippingLine' =>  'MSC',],
            ['vessel' => 'AS POSEIDON', 'shippingLine' =>  'MSC',],
            ['vessel' => 'ASTOR', 'shippingLine' =>  'SCL',],
            ['vessel' => 'ATLANTIC CARTIER', 'shippingLine' =>  'ACL',],
            ['vessel' => 'ATLANTIC COMPANION', 'shippingLine' =>  'ACL',],
            ['vessel' => 'ATLANTIC COMPASS', 'shippingLine' =>  'ACL',],
            ['vessel' => 'ATLANTIC CONCERT', 'shippingLine' =>  'ACL',],
            ['vessel' => 'ATLANTIC CONVEYOR', 'shippingLine' =>  'ACL',],
            ['vessel' => 'ATLANTIC REEFER', 'shippingLine' =>  'ZIM',],
            ['vessel' => 'ATLANTIC VOYAGER', 'shippingLine' =>  'MOL',],
            ['vessel' => 'AZURYT', 'shippingLine' =>  'EUROAFRICA',],
            ['vessel' => 'BACO LINER 1', 'shippingLine' =>  'BACO',],
            ['vessel' => 'BACO LINER 2', 'shippingLine' =>  'BACO',],
            ['vessel' => 'BACO LINER 3', 'shippingLine' =>  'BACO',],
            ['vessel' => 'BAVARIA', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'BEAUMONT', 'shippingLine' =>  'MSC',],
            ['vessel' => 'BLACK SEA', 'shippingLine' =>  'ZIM',],
            ['vessel' => 'BLANDINE DELMAS', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'BOMAR RESILIENT', 'shippingLine' =>  'HAPAG-LLOYD',],
            ['vessel' => 'BOXFORD', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'BUENOS AIRES', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'BUNGA RAYA DUA', 'shippingLine' =>  'MISC',],
            ['vessel' => 'BUNGA RAYA SATU', 'shippingLine' =>  'MISC',],
            ['vessel' => 'BUXFAVORITE', 'shippingLine' =>  'ZIM',],
            ['vessel' => 'BUXLAGOON', 'shippingLine' =>  'MSC',],
            ['vessel' => 'BUXLINK', 'shippingLine' =>  'MOL',],
            ['vessel' => 'BUXSAILOR', 'shippingLine' =>  'ZIM',],
            ['vessel' => 'BUXSTAR', 'shippingLine' =>  'MSC',],
            ['vessel' => 'CALAO', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'CALIFORNIA DRAGON', 'shippingLine' =>  'MSC',],
            ['vessel' => 'CALIFORNIA DRAGON 2R', 'shippingLine' =>  'MSC',],
            ['vessel' => 'CAP AGULHAS', 'shippingLine' =>  'PIL',],
            ['vessel' => 'CAP EGMONT', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'CAPE HATTERAS', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'CAPE MANILLA', 'shippingLine' =>  'MSC',],
            ['vessel' => 'CARIBBEAN STAR', 'shippingLine' =>  'AFRICA EXPRESS LINE',],
            ['vessel' => 'CAROLINA STAR', 'shippingLine' =>  'MARGUISA',],
            ['vessel' => 'CAROLINE DELMAS', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'CATALINA STAR', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'CEC FUTURE', 'shippingLine' =>  'Clipper Project shipping ltd',],
            ['vessel' => 'CELINA STAR', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'CENTAURUS', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'CHAITEN', 'shippingLine' =>  'MSC',],
            ['vessel' => 'CHARLOTTA', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'CHRISTINA I', 'shippingLine' =>  'PORTLINE',],
            ['vessel' => 'CIELO DI AGADIR', 'shippingLine' =>  'MSC',],
            ['vessel' => 'CIRCULAR QUAY', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'CITY OF GUANGZHOU', 'shippingLine' =>  'ARKAS LINES',],
            ['vessel' => 'CITY OF HONG KONG', 'shippingLine' =>  'ARKAS LINES',],
            ['vessel' => 'CLAES MAERSK', 'shippingLine' =>  'ML',],
            ['vessel' => 'CLOU OCEAN', 'shippingLine' =>  'PORTLINE',],
            ['vessel' => 'CMA CGM ACCRA', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'CMA CGM AGUILA', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'CMA CGM AMERICA', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'CMA CGM ANAPURNA', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'CMA CGM AZTECA', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'CMA CGM BRASILIA', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'CMA CGM BUENOS AIRES', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'CMA CGM CAPRICORNE', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'CMA CGM CARIBBEAN', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'CMA CGM COLIBRI', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'CMA CGM COLOMBIE', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'CMA CGM COMOE', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'CMA CGM CORTES', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'CMA CGM ESMERALDA', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'CMA CGM EVEREST', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'CMA CGM IMPALA', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'CMA CGM JAGUAR', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'CMA CGM KAILAS', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'CMA CGM KIWI', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'CMA CGM LA BOUSSOLE', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'CMA CGM LAGOS', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'CMA CGM L\'ASTROLABE', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'CMA CGM L\'ETOILE', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'CMA CGM LIMON', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'CMA CGM MAYA', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'CMA CGM MONTENEGRO', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'CMA CGM NIGER', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'CMA CGM OKAPI', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'CMA CGM OMAN', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'CMA CGM OUBANGUI', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'CMA CGM PARANA', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'CMA CGM PUMA', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'CMA CGM QUETZAL', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'CMA CGM RABAT', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'CMA CGM RIO GRANDE', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'CMA CGM SAMBHAR', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'CMA CGM SANTOS', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'CMA CGM SIMBA', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'CMA CGM TEMA', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'CMA CGM TOGO', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'CMA CGM VICTORIA', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'CMA CGM VOLTA', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'CMA-CGM BUENOS AIRES', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'COLD STREAM', 'shippingLine' =>  'ZIM',],
            ['vessel' => 'COLOMBIAN STAR', 'shippingLine' =>  'AFRICA EXPRESS LINE',],
            ['vessel' => 'COMMANDER', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'COMMODORE', 'shippingLine' =>  'NYK',],
            ['vessel' => 'CONTI ARABELLA', 'shippingLine' =>  'MOL',],
            ['vessel' => 'CONTI CARTAGENA', 'shippingLine' =>  'ML',],
            ['vessel' => 'CONTI CHIWAN', 'shippingLine' =>  'MSC',],
            ['vessel' => 'CONTI EXPRESS', 'shippingLine' =>  'CONTI',],
            ['vessel' => 'CONTI SHARJAH', 'shippingLine' =>  'MSC',],
            ['vessel' => 'CONTI SINGA', 'shippingLine' =>  'MSC',],
            ['vessel' => 'COSTA RICAN STAR', 'shippingLine' =>  'AFRICA EXPRESS LINE',],
            ['vessel' => 'COTE DIVOIRIAN STAR', 'shippingLine' =>  'AFRICA EXPRESS LINE',],
            ['vessel' => 'COTE IVOIRIAN STAR', 'shippingLine' =>  'ZIM',],
            ['vessel' => 'CRISTINA A.', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'CRISTINA STAR', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'CS DISCOVERY', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'CSAV BRASILIA', 'shippingLine' =>  'MSC',],
            ['vessel' => 'CSAV CALLAO', 'shippingLine' =>  'CSAV',],
            ['vessel' => 'CSAV ITAJAI', 'shippingLine' =>  'CSAV',],
            ['vessel' => 'CSAV MOEMA', 'shippingLine' =>  'CSAV',],
            ['vessel' => 'CSAV MORUMBI', 'shippingLine' =>  'CSAV',],
            ['vessel' => 'CSAV NEW YORK', 'shippingLine' =>  'CSAV',],
            ['vessel' => 'CSAV PARANAGUA', 'shippingLine' =>  'CSAV',],
            ['vessel' => 'CSAV RAHUE', 'shippingLine' =>  'CSAV',],
            ['vessel' => 'CSAV RENAICO', 'shippingLine' =>  'CSAV',],
            ['vessel' => 'CSAV TOTORAL', 'shippingLine' =>  'MSC',],
            ['vessel' => 'CSAV TRINIDAD', 'shippingLine' =>  'CSAV',],
            ['vessel' => 'DELMAS BONNY', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'DELMAS BRAZZAVILLE', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'DELMAS KETA', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'DELMAS SEYCHELLES', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'DELPHINE DELMAS', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'DESPINA', 'shippingLine' =>  'MSC',],
            ['vessel' => 'DIAMOND LAND', 'shippingLine' =>  'MACS',],
            ['vessel' => 'DIMITRIS C', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'DORIKOS', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'ECLIPSE', 'shippingLine' =>  'BOLLUDA',],
            ['vessel' => 'EL LOBO', 'shippingLine' =>  'SAILS',],
            ['vessel' => 'EM CHIOS', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'EM ITHAKI', 'shippingLine' =>  'MOL',],
            ['vessel' => 'EM KEA', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'EM PSARA', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'EMERALD', 'shippingLine' =>  'EUROAFRICA',],
            ['vessel' => 'EMILIA', 'shippingLine' =>  'SAILS',],
            ['vessel' => 'ESPERANZA N', 'shippingLine' =>  'MOL',],
            ['vessel' => 'EUROCARGO AFRICA', 'shippingLine' =>  'GRIMALDI',],
            ['vessel' => 'EUROCARGO BARI', 'shippingLine' =>  'GRIMALDI',],
            ['vessel' => 'EUROCARGO EUROPA', 'shippingLine' =>  'GRIMALDI',],
            ['vessel' => 'EUROCARGO ISTAMBUL', 'shippingLine' =>  'GRIMALDI',],
            ['vessel' => 'EUROCARGO SALERNO', 'shippingLine' =>  'GRIMALDI',],
            ['vessel' => 'FESCO ASKOLD', 'shippingLine' =>  'MSC',],
            ['vessel' => 'FRANCISCA SCHULTE', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'FRIJSENBORG', 'shippingLine' =>  'NORDANA',],
            ['vessel' => 'FRISIA HANNOVER', 'shippingLine' =>  'MOL',],
            ['vessel' => 'FRISIA HELSINKI', 'shippingLine' =>  'MOL',],
            ['vessel' => 'FRISIA LUBECK', 'shippingLine' =>  'MOL',],
            ['vessel' => 'FRISIA ROSTOCK', 'shippingLine' =>  'MOL',],
            ['vessel' => 'GARNET ACE', 'shippingLine' =>  'MOL',],
            ['vessel' => 'GEORG SCHULTE', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'GERD', 'shippingLine' =>  'MSC',],
            ['vessel' => 'GISELE A', 'shippingLine' =>  'ARKAS LINES',],
            ['vessel' => 'GOLDEN ISLE', 'shippingLine' =>  'MACS',],
            ['vessel' => 'GRANAT', 'shippingLine' =>  'EUROAFRICA',],
            ['vessel' => 'GRAND VISION', 'shippingLine' =>  'MSC',],
            ['vessel' => 'GRANDE AFRICA', 'shippingLine' =>  'GRIMALDI',],
            ['vessel' => 'GRANDE AMBURGO', 'shippingLine' =>  'GRIMALDI',],
            ['vessel' => 'GRANDE AMERICA', 'shippingLine' =>  'GRIMALDI',],
            ['vessel' => 'GRANDE ANGOLA', 'shippingLine' =>  'GRIMALDI',],
            ['vessel' => 'GRANDE ARGENTINA', 'shippingLine' =>  'GRIMALDI',],
            ['vessel' => 'GRANDE ATLANTICO', 'shippingLine' =>  'GRIMALDI',],
            ['vessel' => 'GRANDE BENIN', 'shippingLine' =>  'GRIMALDI',],
            ['vessel' => 'GRANDE BRASILE', 'shippingLine' =>  'GRIMALDI',],
            ['vessel' => 'GRANDE BUENOS AIRES', 'shippingLine' =>  'GRIMALDI',],
            ['vessel' => 'GRANDE C. D\'AVORIO', 'shippingLine' =>  'GRIMALDI',],
            ['vessel' => 'GRANDE CAMEROON', 'shippingLine' =>  'GRIMALDI',],
            ['vessel' => 'GRANDE CONGO', 'shippingLine' =>  'GRIMALDI',],
            ['vessel' => 'GRANDE COSTA', 'shippingLine' =>  'GRIMALDI',],
            ['vessel' => 'GRANDE COSTA D AVORI', 'shippingLine' =>  'GRIMALDI',],
            ['vessel' => 'GRANDE COSTA D\'AVORIO', 'shippingLine' =>  'GRIMALDI',],
            ['vessel' => 'GRANDE FRANCIA', 'shippingLine' =>  'GRIMALDI',],
            ['vessel' => 'GRANDE GABON', 'shippingLine' =>  'GRIMALDI',],
            ['vessel' => 'GRANDE GHANA', 'shippingLine' =>  'GRIMALDI',],
            ['vessel' => 'GRANDE GUINEA', 'shippingLine' =>  'GRIMALDI',],
            ['vessel' => 'GRANDE LAGOS', 'shippingLine' =>  'GRIMALDI',],
            ['vessel' => 'GRANDE MAROCCO', 'shippingLine' =>  'GRIMALDI',],
            ['vessel' => 'GRANDE MOROCCO', 'shippingLine' =>  'GRIMALDI',],
            ['vessel' => 'GRANDE NIGERIA', 'shippingLine' =>  'GRIMALDI',],
            ['vessel' => 'GRANDE SAN PAOLO', 'shippingLine' =>  'GRIMALDI',],
            ['vessel' => 'GRANDE SENEGAL', 'shippingLine' =>  'GRIMALDI',],
            ['vessel' => 'GRANDE SIERRA LEONE', 'shippingLine' =>  'GRIMALDI',],
            ['vessel' => 'GRANDE TOGO', 'shippingLine' =>  'GRIMALDI',],
            ['vessel' => 'GREEN CAPE', 'shippingLine' =>  'MACS',],
            ['vessel' => 'GULBENIZ A.', 'shippingLine' =>  'ARKAS LINES',],
            ['vessel' => 'GUSTAV SCHULTE', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'HAMMONIA PACIFICUM', 'shippingLine' =>  'NYK',],
            ['vessel' => 'HANNES C.', 'shippingLine' =>  'PORTLINE',],
            ['vessel' => 'HANSA CATALINA', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'HANSA CENTURION', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'HANSA CLOPPENBURG', 'shippingLine' =>  'HAPAG-LLOYD',],
            ['vessel' => 'HANSA FREYBURG', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'HANSA LIMBURG', 'shippingLine' =>  'HAPAG-LLOYD',],
            ['vessel' => 'HANSA MARBURG', 'shippingLine' =>  'HAPAG-LLOYD',],
            ['vessel' => 'HANSA NARVIK', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'HANSA RIGA', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'HANSA VICTORY', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'HEBE', 'shippingLine' =>  'MSC',],
            ['vessel' => 'HELENE J', 'shippingLine' =>  'MESSINA',],
            ['vessel' => 'HELENE RUSS', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'HELLE RITSCHER', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'HELMUT', 'shippingLine' =>  'MSC',],
            ['vessel' => 'HERMANN HESSE', 'shippingLine' =>  'MOL',],
            ['vessel' => 'HISPANIA', 'shippingLine' =>  'PORTLINE',],
            ['vessel' => 'HOPE', 'shippingLine' =>  'MSC',],
            ['vessel' => 'HS BERLIOZ', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'HS CHOPIN', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'HS DISCOVERER', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'HS LIVINGSTONE', 'shippingLine' =>  'MSC',],
            ['vessel' => 'HS SCOOT', 'shippingLine' =>  'MSC',],
            ['vessel' => 'ISABELLE SCHULTE', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'ISOLDE', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'IWASHIRO', 'shippingLine' =>  'PIL',],
            ['vessel' => 'JANA', 'shippingLine' =>  'MSC',],
            ['vessel' => 'JOLLY ARGENTO', 'shippingLine' =>  'MESSINA',],
            ['vessel' => 'JOLLY BIANCO', 'shippingLine' =>  'MESSINA',],
            ['vessel' => 'JOLLY CORALLO', 'shippingLine' =>  'MESSINA',],
            ['vessel' => 'JOLLY MARONE', 'shippingLine' =>  'MESSINA',],
            ['vessel' => 'JOLLY ROSSO', 'shippingLine' =>  'MESSINA',],
            ['vessel' => 'JOLLY VERDE', 'shippingLine' =>  'MESSINA',],
            ['vessel' => 'JOLLY ZAFFIRO', 'shippingLine' =>  'MESSINA',],
            ['vessel' => 'JONNI RITSCHER', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'JPO GEMINI', 'shippingLine' =>  'ML',],
            ['vessel' => 'JULIA SCHULTE', 'shippingLine' =>  'ML',],
            ['vessel' => 'JULIE DELMAS', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'KARIN S', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'KEMAL A', 'shippingLine' =>  'ARKAS LINES',],
            ['vessel' => 'KERSTIN S', 'shippingLine' =>  'ML',],
            ['vessel' => 'KING JUSTUS', 'shippingLine' =>  'MSC',],
            ['vessel' => 'KLAUS J', 'shippingLine' =>  'MESSINA',],
            ['vessel' => 'KOLLMAR', 'shippingLine' =>  'MESSINA',],
            ['vessel' => 'KOMODO', 'shippingLine' =>  'MSC',],
            ['vessel' => 'KONRAD SCHULTE', 'shippingLine' =>  'HAPAG-LLOYD',],
            ['vessel' => 'KOTA AKBAR', 'shippingLine' =>  'PIL',],
            ['vessel' => 'KOTA ANGGERIK', 'shippingLine' =>  'PIL',],
            ['vessel' => 'KOTA ANGGUN', 'shippingLine' =>  'PIL',],
            ['vessel' => 'KOTA ARIF', 'shippingLine' =>  'PIL',],
            ['vessel' => 'KOTA AZAM', 'shippingLine' =>  'PIL',],
            ['vessel' => 'KOTA BAHAGIA', 'shippingLine' =>  'PIL',],
            ['vessel' => 'KOTA BERANI', 'shippingLine' =>  'PIL',],
            ['vessel' => 'KOTA BERJAYA', 'shippingLine' =>  'PIL',],
            ['vessel' => 'KOTA BERKAT', 'shippingLine' =>  'PIL',],
            ['vessel' => 'KOTA BERLIAN', 'shippingLine' =>  'PIL',],
            ['vessel' => 'KOTA HAKIM', 'shippingLine' =>  'PIL',],
            ['vessel' => 'KOTA HALUS', 'shippingLine' =>  'PIL',],
            ['vessel' => 'KOTA HANDAL', 'shippingLine' =>  'PIL',],
            ['vessel' => 'KOTA HAPAS', 'shippingLine' =>  'PIL',],
            ['vessel' => 'KOTA HARUM', 'shippingLine' =>  'PIL',],
            ['vessel' => 'KOTA HENING', 'shippingLine' =>  'PIL',],
            ['vessel' => 'KOTA KAMIL', 'shippingLine' =>  'PIL',],
            ['vessel' => 'KOTA KARIM', 'shippingLine' =>  'PIL',],
            ['vessel' => 'KOTA KAYA', 'shippingLine' =>  'PIL',],
            ['vessel' => 'KOTA MANIS', 'shippingLine' =>  'PIL',],
            ['vessel' => 'KOTA MAWAR', 'shippingLine' =>  'PIL',],
            ['vessel' => 'KOTA MESRA', 'shippingLine' =>  'PIL',],
            ['vessel' => 'KOTA SABAS', 'shippingLine' =>  'PIL',],
            ['vessel' => 'LADY ROSE', 'shippingLine' =>  'AFRICA EXPRESS LINE',],
            ['vessel' => 'LADY ROSEBAY', 'shippingLine' =>  'AFRICA EXPRESS LINE',],
            ['vessel' => 'LADY ROSEBUD', 'shippingLine' =>  'AFRICA EXPRESS LINE',],
            ['vessel' => 'LADY ROSEMARY', 'shippingLine' =>  'AFRICA EXPRESS LINE',],
            ['vessel' => 'LAURA DELMAS', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'LAURA MAERSK', 'shippingLine' =>  'ML',],
            ['vessel' => 'LAUST MAERSK', 'shippingLine' =>  'ML',],
            ['vessel' => 'LEDA MAERSK', 'shippingLine' =>  'ML',],
            ['vessel' => 'LEDA TRADER', 'shippingLine' =>  'MSC',],
            ['vessel' => 'LEXA MAERSK', 'shippingLine' =>  'ML',],
            ['vessel' => 'LICA MAERSK', 'shippingLine' =>  'ML',],
            ['vessel' => 'LIRCAY', 'shippingLine' =>  'CSAV',],
            ['vessel' => 'LONDON TOWER', 'shippingLine' =>  'PIL',],
            ['vessel' => 'LOUISA SCHULTE', 'shippingLine' =>  'MESSINA',],
            ['vessel' => 'LUCIE DELMAS', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'LUNA MAERSK', 'shippingLine' =>  'ML',],
            ['vessel' => 'MACAO STRAIT', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'MACUBA', 'shippingLine' =>  'SCL',],
            ['vessel' => 'MAERSK NEUSTADT', 'shippingLine' =>  'ML',],
            ['vessel' => 'MAERSK WILMINGTON', 'shippingLine' =>  'ML',],
            ['vessel' => 'MAERSK WINDHOEK', 'shippingLine' =>  'ML',],
            ['vessel' => 'MAESTRO OCEAN', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'MAESTRO SEA', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'MAESTRO SUN', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'MAESTRO UNIVERSE', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'MALACHIT', 'shippingLine' =>  'EUROAFRICA',],
            ['vessel' => 'MANX LION', 'shippingLine' =>  'PORTLINE',],
            ['vessel' => 'MARE CARIBICUM', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MARGARETE SCHULTE', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'MARIE DELMAS', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'MARIENBORG', 'shippingLine' =>  'NORDANA',],
            ['vessel' => 'MARINA', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'MARIO A.', 'shippingLine' =>  'ML',],
            ['vessel' => 'MARIVIA', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'MARMARA SEA', 'shippingLine' =>  'ZIM',],
            ['vessel' => 'MARUBA CRISTINA', 'shippingLine' =>  'MARUBA',],
            ['vessel' => 'MATE', 'shippingLine' =>  'NYK',],
            ['vessel' => 'MAULE', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MAXINE', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MCP VIENNA', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MCS AMERICA', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MERCHANT', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MERKUR', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'MERKUR BAY', 'shippingLine' =>  'NYK',],
            ['vessel' => 'MICHAELA S.', 'shippingLine' =>  'ML',],
            ['vessel' => 'MICHEL A.', 'shippingLine' =>  'SCL',],
            ['vessel' => 'MISC DARLINGTON', 'shippingLine' =>  'MISC',],
            ['vessel' => 'MN CALAO', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'MOL', 'shippingLine' =>  'MOL',],
            ['vessel' => 'MOL HONOR', 'shippingLine' =>  'MOL',],
            ['vessel' => 'MOL SASSANDRA', 'shippingLine' =>  'MOL',],
            ['vessel' => 'MOL SEABREEZE', 'shippingLine' =>  'MOL',],
            ['vessel' => 'MOL STABILITY', 'shippingLine' =>  'MOL',],
            ['vessel' => 'MOL SYMPHONY', 'shippingLine' =>  'MOL',],
            ['vessel' => 'MOL VALPARAISO', 'shippingLine' =>  'MOL',],
            ['vessel' => 'MOL VOLTA', 'shippingLine' =>  'MOL',],
            ['vessel' => 'MSC ACCRA', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC ADRIATIC', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC AFRICA', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC AGATA', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC ALABAMA', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC ALEXA', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC ALEXANDRA', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC ALICANTE', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC AMERICA', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC AMSTERDAM', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC ASTRID', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC ATLANTIC', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC BARBARA', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC BENEDETTA', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC BORNEO', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC BREMEN', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC BROOKE', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC BULGARIA', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC CANBERRA', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC CATANIA', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC CHANECA', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC CHIARA', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC CONFIDENCE', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC CORINNA', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC DENISSE', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC DIDEM', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC DON GIOVANNI', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC DONATA', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC DYMPHNA', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC ELA', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC ELENI', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC ELEONORA', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC ELOISE', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC EMIHRAN', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC EMMA', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC ENGLAND', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC EUGENIA', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC FABIENNE', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC FEDERICA', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC FINLAND', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC FLAMINIA', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC FLORIANA', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC GABRIELLA', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC GINA', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC GRACE', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC HAILEY', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC HARMONY', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC HIMALAYA', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC INDIA', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC ISABELLE', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC ISHYKA', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC ITEA', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC JADE', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC JAPAN', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC JASMINE', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC JENNY', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC JILHAN', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC JORDAN', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC KERRY', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC KOREA', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC LARA', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC LAURA', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC LAUREN', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC LAURENCE', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC LAUSANNE', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC LEA', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC LEILA', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC LEVINA', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC LISBON', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC LONDON', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC LONGONI', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC LORENA', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC LORETTA', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC LUCIA', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC LUGANO', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC LUISA', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC MAHIMA', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC MANDY', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC MARA', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC MARIA LAURA', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC MARIANNA', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC MARTINA', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC MASCARET', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC MATILDE', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC MAUREEN', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC MAYA', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC MEDITERRANEAN', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC MESSINA', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC METHONI', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC MICHAELA', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC MIRELLA', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC MONICA', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC NAMIBIA', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC NATALIA', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC NEDERLAND', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC NOA', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC NORMANDIE', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC OLGA', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC PANAMA', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC PAOLA', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC PAOLO', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC PATRICIA', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC PILAR', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC PRAGUE', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC RAFAELA', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC REBECCA', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC REGINA', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC RITA', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC RONIT', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC ROSSELLA', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC SABRINA', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC SAMANTHA', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC SANDRA', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC SANTHYA', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC SCOTLAND', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC SELIN', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC SERENA', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC SHANNON', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC SHARJAH', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC SHIRLEY', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC SIERRA II', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC SONIA', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC SOPHIE', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC STEFANIA', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC STELLA', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC SUDAN', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC SUEZ', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC TOBA', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC UKRAINE', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC ULSAN', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC VALERIA', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC VANESSA', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC VERONIQUE', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC VIENNA', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC VOLTA', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC VOYAGER', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC WASHINGTON', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC ZANZIBAR', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC ZURICH', 'shippingLine' =>  'MSC',],
            ['vessel' => 'NAIROBI', 'shippingLine' =>  'MSC',],
            ['vessel' => 'NATALIE SCHULTE', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'NEDLLOYD EVITA', 'shippingLine' =>  'ML',],
            ['vessel' => 'NEDLLOYD TESLIN', 'shippingLine' =>  'ML',],
            ['vessel' => 'NEFRYT', 'shippingLine' =>  'EUROAFRICA',],
            ['vessel' => 'NEPTUN', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'NICOLAS DELMAS', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'NIKOLAS', 'shippingLine' =>  'MSC',],
            ['vessel' => 'NORDRIVER', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'NORDSTRAND', 'shippingLine' =>  'CSAV',],
            ['vessel' => 'NORTHERN DEBONAIR', 'shippingLine' =>  'MSC',],
            ['vessel' => 'NORTHERN HAPPINESS', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'NOVIA', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'NYK ESTRELA', 'shippingLine' =>  'NYK',],
            ['vessel' => 'NYK FLORESTA', 'shippingLine' =>  'NYK',],
            ['vessel' => 'OCEAN PROTECTOR', 'shippingLine' =>  'MSC',],
            ['vessel' => 'OLIVIA', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'ONYX', 'shippingLine' =>  'EUROAFRICA',],
            ['vessel' => 'ORINOCO RIVER', 'shippingLine' =>  'SAILS',],
            ['vessel' => 'OXL LOTUS', 'shippingLine' =>  'BOLLUDA',],
            ['vessel' => 'PACIFIC EXPRESS', 'shippingLine' =>  'CONTI',],
            ['vessel' => 'PARIS', 'shippingLine' =>  'PIL',],
            ['vessel' => 'PATRICIA SCHULTE', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'PCE MADEIRA', 'shippingLine' =>  'ML',],
            ['vessel' => 'PEARL RIVER', 'shippingLine' =>  'MSC',],
            ['vessel' => 'PELICAN', 'shippingLine' =>  'BOLLUDA',],
            ['vessel' => 'PENELOPE', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'PETKUM', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'PLUTO', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'POLARIS', 'shippingLine' =>  'MSC',],
            ['vessel' => 'PORT TEJO', 'shippingLine' =>  'PORTLINE',],
            ['vessel' => 'PORTOFINO', 'shippingLine' =>  'GRIMALDI',],
            ['vessel' => 'PRAIA', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'PRIMAVERA', 'shippingLine' =>  'MSC',],
            ['vessel' => 'PRIMUS', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'PRIWALL', 'shippingLine' =>  'MSC',],
            ['vessel' => 'PUCON', 'shippingLine' =>  'MSC',],
            ['vessel' => 'QUEEN OF LUCK', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'R. R. AMERICA', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'R; SEA', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'REGAL STAR', 'shippingLine' =>  'ZIM',],
            ['vessel' => 'REPUBBLICA ARGENTINA', 'shippingLine' =>  'GRIMALDI',],
            ['vessel' => 'REPUBBLICA DEL BRASILE', 'shippingLine' =>  'GRIMALDI',],
            ['vessel' => 'REPUBBLICA DI AMALFI', 'shippingLine' =>  'GRIMALDI',],
            ['vessel' => 'REPUBBLICA DI ROMA', 'shippingLine' =>  'GRIMALDI',],
            ['vessel' => 'REPUBBLICA DI VENEZIA', 'shippingLine' =>  'GRIMALDI',],
            ['vessel' => 'RHL AQUA', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'RHLAQUA', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'RIO DE JANEIRO', 'shippingLine' =>  'MSC',],
            ['vessel' => 'RIO TESLIN', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'RIO THOMPSON', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'ROSA DELMAS', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'ROSBORG', 'shippingLine' =>  'NORDANA',],
            ['vessel' => 'ROTORUA', 'shippingLine' =>  'HAPAG-LLOYD',],
            ['vessel' => 'SAFMARINE PANTANAL', 'shippingLine' =>  'SCL',],
            ['vessel' => 'SAFMARINE SALOUM', 'shippingLine' =>  'SCL',],
            ['vessel' => 'SAFMARINE SANAGA', 'shippingLine' =>  'SCL',],
            ['vessel' => 'SAG WESTFALEN', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'SAN FELIPE', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'SAN FERNANDO', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'SAN FRANCISCO', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'SANTA GIORGINA', 'shippingLine' =>  'MOL',],
            ['vessel' => 'SANTA MADDALENA', 'shippingLine' =>  'CSAV',],
            ['vessel' => 'SANTA MONICA', 'shippingLine' =>  'MSC',],
            ['vessel' => 'SAWASDEE HONGKONG', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'SAWASDEE JAKARTA', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'SCL BERN', 'shippingLine' =>  'Swiss Cargo Line',],
            ['vessel' => 'SCT CHILE', 'shippingLine' =>  'MSC',],
            ['vessel' => 'SEA BREEZE', 'shippingLine' =>  'GRIMALDI',],
            ['vessel' => 'Select Vessel Name', 'shippingLine' =>  'Operator',],
            ['vessel' => 'SHANTI', 'shippingLine' =>  'ML',],
            ['vessel' => 'SIMA SINGAPORE', 'shippingLine' =>  'MSC',],
            ['vessel' => 'SLOMAN PRODUCER', 'shippingLine' =>  'BOLLUDA',],
            ['vessel' => 'SPERO', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'SPIRIT OF CAPETOWN', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'STADT SCHWERIN', 'shippingLine' =>  'SCL',],
            ['vessel' => 'STAR SERVICE', 'shippingLine' =>  'ZIM',],
            ['vessel' => 'STAR STANDARD', 'shippingLine' =>  'ZIM',],
            ['vessel' => 'STAR TRUST', 'shippingLine' =>  'ZIM',],
            ['vessel' => 'START FIRST', 'shippingLine' =>  'ZIM',],
            ['vessel' => 'STELLENBOSCH', 'shippingLine' =>  'MACS',],
            ['vessel' => 'STRAUSS', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'SURINAM RIVER', 'shippingLine' =>  'SCL',],
            ['vessel' => 'SZAFIR', 'shippingLine' =>  'EUROAFRICA',],
            ['vessel' => 'TAGA BAY', 'shippingLine' =>  'SAILS',],
            ['vessel' => 'TAMPA BAY', 'shippingLine' =>  'CSAV',],
            ['vessel' => 'TASMANIA', 'shippingLine' =>  'MSC',],
            ['vessel' => 'TERRA BONA', 'shippingLine' =>  'PIL',],
            ['vessel' => 'TERRA LUMINA', 'shippingLine' =>  'PIL',],
            ['vessel' => 'TERRY DOS', 'shippingLine' =>  'CABOMUNDO',],
            ['vessel' => 'TERRY SIETE', 'shippingLine' =>  'CABOMUNDO',],
            ['vessel' => 'TERRY TRES', 'shippingLine' =>  'CABOMUNDO',],
            ['vessel' => 'THASOS', 'shippingLine' =>  'MSC',],
            ['vessel' => 'THEBELAND', 'shippingLine' =>  'GRIMALDI',],
            ['vessel' => 'THORSWAVE', 'shippingLine' =>  'ZIM',],
            ['vessel' => 'THURÖ MAERSK', 'shippingLine' =>  'ML',],
            ['vessel' => 'TOKATA', 'shippingLine' =>  'MSC',],
            ['vessel' => 'TRAVE TRADER', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'TROENSE MAERSK', 'shippingLine' =>  'ML',],
            ['vessel' => 'TROYBURG', 'shippingLine' =>  'PIL',],
            ['vessel' => 'TYRUSLAND', 'shippingLine' =>  'GRIMALDI',],
            ['vessel' => 'ULYSSES', 'shippingLine' =>  'MOL',],
            ['vessel' => 'URANUS', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'UTE OLTMANN', 'shippingLine' =>  'MSC',],
            ['vessel' => 'VAAL RIVER', 'shippingLine' =>  'SAILS',],
            ['vessel' => 'VERO B', 'shippingLine' =>  'BOLLUDA',],
            ['vessel' => 'VERO B.', 'shippingLine' =>  'BOLLUDA',],
            ['vessel' => 'VIOLET', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'VIRANA', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'VITALITY', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'WEC GOYA', 'shippingLine' =>  'MSC',],
            ['vessel' => 'WEC SOROLLA', 'shippingLine' =>  'MSC',],
            ['vessel' => 'WEC VELAZQUEZ', 'shippingLine' =>  'MSC',],
            ['vessel' => 'WEDELLSBORG', 'shippingLine' =>  'NORDANA',],
            ['vessel' => 'WEHR ALSTER', 'shippingLine' =>  'ARKAS LINES',],
            ['vessel' => 'WEHR ELBE', 'shippingLine' =>  'MOL',],
            ['vessel' => 'WEHR HAVEL', 'shippingLine' =>  'ARKAS LINES',],
            ['vessel' => 'WEHR OSTE', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'WEHR WESER', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'WESTERHAMM', 'shippingLine' =>  'MSC',],
            ['vessel' => 'WESTERMOOR', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'WESTERTAL', 'shippingLine' =>  'MSC',],
            ['vessel' => 'WILD LOTUS', 'shippingLine' =>  'MOL',],
            ['vessel' => 'YK SASSANDRA', 'shippingLine' =>  'MOL',],
            ['vessel' => 'ZAGORA', 'shippingLine' =>  'MSC',],
            ['vessel' => 'ZERAN', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'MSC GIORGIA', 'shippingLine' =>  'MSC',],
            ['vessel' => 'CMA CGM MEKNES', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'GULBENIZ A', 'shippingLine' =>  'ZIM',],
            ['vessel' => 'MONA LISA', 'shippingLine' =>  'MSC',],
            ['vessel' => 'HANSE RELIANCE', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'PARTICI', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'DELMAS SWALA', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'SCL ANGELA', 'shippingLine' =>  'Swiss Cargo Line',],
            ['vessel' => 'ORIENT SPIRIT', 'shippingLine' =>  'ACL',],
            ['vessel' => 'GRANDE TEMA', 'shippingLine' =>  'GRIMALDI',],
            ['vessel' => 'ATLANTIC NAVIGATOR', 'shippingLine' =>  'CSAL',],
            ['vessel' => 'SONOMA', 'shippingLine' =>  'MESSINA',],
            ['vessel' => 'MSC BANU', 'shippingLine' =>  'MSC',],
            ['vessel' => 'CALISTO', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'LUDWIG SCHULTE', 'shippingLine' =>  'HAPAG-LLOYD',],
            ['vessel' => 'NIMET', 'shippingLine' =>  'BOLLUDA',],
            ['vessel' => 'GRANDE COTONOU', 'shippingLine' =>  'GRIMALDI',],
            ['vessel' => 'HOEGH TRANSPORTER', 'shippingLine' =>  'HOEGH AUTOLINERS',],
            ['vessel' => 'GRANDE SANTHYA', 'shippingLine' =>  'GRIMALDI',],
            ['vessel' => 'THORCO HILDE', 'shippingLine' =>  'THORCO SHIPPING',],
            ['vessel' => 'JSP LEVANTE', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'MILAN TRADER', 'shippingLine' =>  'MESSINA',],
            ['vessel' => 'PACIFIC REEFER', 'shippingLine' =>  'ZIM',],
            ['vessel' => 'NOMADIC MILDE', 'shippingLine' =>  'NOMADIC',],
            ['vessel' => 'ATHENA', 'shippingLine' =>  'MSC',],
            ['vessel' => 'ELBINSEL', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'ISODORA', 'shippingLine' =>  'ARKAS LINES',],
            ['vessel' => 'PETALIDI', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'MOEN ISLAND', 'shippingLine' =>  'HAPAG-LLOYD',],
            ['vessel' => 'DURANDE', 'shippingLine' =>  'HAPAG-LLOYD',],
            ['vessel' => 'MSC NAMIBIA II', 'shippingLine' =>  'MSC',],
            ['vessel' => 'GRANDE ABIDJAN', 'shippingLine' =>  'GRIMALDI',],
            ['vessel' => 'GRANDE LUANDA', 'shippingLine' =>  'GRIMALDI',],
            ['vessel' => 'CMA CGM AFRICA ONE', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'ALTINIA', 'shippingLine' =>  'MNM AFRICAN SHIPPING',],
            ['vessel' => 'TANGARA', 'shippingLine' =>  'ZIM',],
            ['vessel' => 'CMA CGM AFRICA FOUR', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'HOEGH TROOPER', 'shippingLine' =>  'HOEGH AUTOLINERS',],
            ['vessel' => 'MV MARTIN', 'shippingLine' =>  'HAPAG-LLOYD',],
            ['vessel' => 'VIVIEN A', 'shippingLine' =>  'HAPAG-LLOYD',],
            ['vessel' => 'LIBERTY ACE', 'shippingLine' =>  'ZIM',],
            ['vessel' => 'MERITIUS', 'shippingLine' =>  'ZIM',],
            ['vessel' => 'CMA CGM AFRICA TWO', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'THORCO AURORA', 'shippingLine' =>  'THORCO SHIPPING',],
            ['vessel' => 'PAGNA', 'shippingLine' =>  'ZIM',],
            ['vessel' => 'CMA CGM AFRICA THREE', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'LIEKE', 'shippingLine' =>  'NOORDRIVER SHIPPING',],
            ['vessel' => 'MORNING LUCY', 'shippingLine' =>  'EUKOR',],
            ['vessel' => 'CARY RICKMERS', 'shippingLine' =>  'RICKMERS GROUP',],
            ['vessel' => 'SEBRING EXPRESS', 'shippingLine' =>  'SALLAUM LINES',],
            ['vessel' => 'GLOVIS CROWN', 'shippingLine' =>  'HYUNDAI GLOVIS',],
            ['vessel' => 'M/V SPAR SPICA', 'shippingLine' =>  'SPAR SHIPPING',],
            ['vessel' => 'GLOVIS SUMMIT', 'shippingLine' =>  'HYUNDAI GLOVIS',],
            ['vessel' => 'ESL EUROPA', 'shippingLine' =>  'ZIM',],
            ['vessel' => 'SILVER SKY', 'shippingLine' =>  'SALLAUM LINES',],
            ['vessel' => 'ALLIANCE NORFOLK', 'shippingLine' =>  'ALLIANCE NAVIGATION',],
            ['vessel' => 'BALTIC MERCUR II', 'shippingLine' =>  'ATLANTIC RO-RO CARRIERS',],
            ['vessel' => 'MURORAN', 'shippingLine' =>  'BREADBOX SHIPPING LINES',],
            ['vessel' => 'WANDA A', 'shippingLine' =>  'HAPAG-LLOYD',],
            ['vessel' => 'MSC ANIELLO', 'shippingLine' =>  'MSC',],
            ['vessel' => 'VIKING EAGLE', 'shippingLine' =>  'HAPAG-LLOYD',],
            ['vessel' => 'LEONIE P', 'shippingLine' =>  'BOLLUDA',],
            ['vessel' => 'WAF PASSION', 'shippingLine' =>  'BOCS',],
            ['vessel' => 'CORSICA LINEA DUI', 'shippingLine' =>  'CORSICA LINEA',],
            ['vessel' => 'TIP HELSINKI', 'shippingLine' =>  'CARISBROOKE SHIPPING',],
            ['vessel' => 'CMA CGM AGADIR', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'THOR COMMANDER', 'shippingLine' =>  'THORCO SHIPPING',],
            ['vessel' => 'TRADE NAVIGATOR', 'shippingLine' =>  'FORESTWAVE NAVIGATION',],
            ['vessel' => 'MV TASMAN MERMAID', 'shippingLine' =>  'HAPAG-LLOYD',],
            ['vessel' => 'FRISIA KIEL', 'shippingLine' =>  'ZIM',],
            ['vessel' => 'HOHEPLATE', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'CORCOVADO', 'shippingLine' =>  'ARKAS LINES',],
            ['vessel' => 'KATHARINAS', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'BALTIC PATRIOT', 'shippingLine' =>  'BALTIC REEFERS',],
            ['vessel' => 'MATAR N', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'YANKI A', 'shippingLine' =>  'ARKAS LINES',],
            ['vessel' => 'THORCO ROYAL', 'shippingLine' =>  'THORCO SHIPPING	',],
            ['vessel' => 'REPULSE BAY', 'shippingLine' =>  'ZIM',],
            ['vessel' => 'DEVON STRAIT', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'VIRGINIA TRADER', 'shippingLine' =>  'LOMAR SHIPPING',],
            ['vessel' => 'MAX WINNER', 'shippingLine' =>  'ZIM',],
            ['vessel' => 'MSC DIEGO', 'shippingLine' =>  'MSC',],
            ['vessel' => 'LAYLA', 'shippingLine' =>  'ZIM',],
            ['vessel' => 'SEATRADE ORANGE', 'shippingLine' =>  'ZIM',],
            ['vessel' => 'MORNING CHAMPION', 'shippingLine' =>  'EUKOR',],
            ['vessel' => 'MSC JOY', 'shippingLine' =>  'MSC',],
            ['vessel' => 'THORCO ARCTIC', 'shippingLine' =>  'THORCO SHIPPING	',],
            ['vessel' => 'AS PALATIA', 'shippingLine' =>  'MESSINA',],
            ['vessel' => 'MSC SHAULA', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC MONTEREY', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC LEIGH', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC CARMEN', 'shippingLine' =>  'MSC',],
            ['vessel' => 'BBC MARMARA', 'shippingLine' =>  'BRIESE SHIPPING',],
            ['vessel' => 'TIM-S', 'shippingLine' =>  'MSC',],
            ['vessel' => 'CORSAIR', 'shippingLine' =>  'ZIM',],
            ['vessel' => 'ADELHEID-S', 'shippingLine' =>  'MSC',],
            ['vessel' => 'SAN FERNANDO REY', 'shippingLine' =>  'TSCHUDI SHIPPING',],
            ['vessel' => 'MV FRIA', 'shippingLine' =>  'CAFISERVICE SPA',],
            ['vessel' => 'MSC KATYAYNI', 'shippingLine' =>  'MSC',],
            ['vessel' => 'OREGON TRADER', 'shippingLine' =>  'HAPAG-LLOYD',],
            ['vessel' => 'HOEGH COPENHAGEN', 'shippingLine' =>  'HOEGH AUTOLINERS',],
            ['vessel' => 'MV THORCO CRYSTAL', 'shippingLine' =>  'THORCO SHIPPING	',],
            ['vessel' => 'THORCO LEGION', 'shippingLine' =>  'THORCO SHIPPING	',],
            ['vessel' => 'MSC ANAHITA', 'shippingLine' =>  'MSC',],
            ['vessel' => 'HOHEWEG', 'shippingLine' =>  'BOLLUDA',],
            ['vessel' => 'FRANCOISE GILOT', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'GRANDE DAKAR', 'shippingLine' =>  'GRIMALDI',],
            ['vessel' => 'IRENES REMEDY', 'shippingLine' =>  'HAPAG-LLOYD',],
            ['vessel' => 'FRISIA OSLO', 'shippingLine' =>  'HAPAG-LLOYD',],
            ['vessel' => 'ABIDJAN EXPRESS', 'shippingLine' =>  'HAPAG-LLOYD',],
            ['vessel' => 'HANSA RENDSBURG', 'shippingLine' =>  'HAPAG-LLOYD',],
            ['vessel' => 'GALA TRIO', 'shippingLine' =>  'TRIO SHIPPING',],
            ['vessel' => 'ASIATIC LIBERTY', 'shippingLine' =>  'ASIATIC LLOYD',],
            ['vessel' => 'FLEUR N', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'V ARCTIC TERN', 'shippingLine' =>  'TBS SHIPPING SERVICES',],
            ['vessel' => 'THORCO MANATEE', 'shippingLine' =>  'THORCO SHIPPING	',],
            ['vessel' => 'RHL AUDACIA', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'MSC ROSARIA', 'shippingLine' =>  'MSC',],
            ['vessel' => 'KENT TRADER', 'shippingLine' =>  'LOMAR SHIPPING',],
            ['vessel' => 'BUXTEHUDE', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MAX WONDER', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'MSC ANGELA', 'shippingLine' =>  'MSC',],
            ['vessel' => 'SONGA ANTOFAGASTA', 'shippingLine' =>  'MSC',],
            ['vessel' => 'SONGA ALYA', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC KORONI', 'shippingLine' =>  'MSC',],
            ['vessel' => 'CALAIS TRADER', 'shippingLine' =>  'MESSINA',],
            ['vessel' => 'PARIS JR', 'shippingLine' =>  'MSC',],
            ['vessel' => 'AS CARELIA', 'shippingLine' =>  'HAPAG-LLOYD',],
            ['vessel' => 'IRENES RAINBOW', 'shippingLine' =>  'MESSINA',],
            ['vessel' => 'MIMMI SCHULTE', 'shippingLine' =>  'AFRICA EXPRESS LINE',],
            ['vessel' => 'THORCO GLORY', 'shippingLine' =>  'THORCO SHIPPING	',],
            ['vessel' => 'SEASPAN JAKARTA', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'MSC CORUNA', 'shippingLine' =>  'MSC',],
            ['vessel' => 'CAPE MANILA', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC VIGO', 'shippingLine' =>  'MSC',],
            ['vessel' => 'HARMONY N', 'shippingLine' =>  'HAPAG-LLOYD',],
            ['vessel' => 'SOLSTICE N', 'shippingLine' =>  'MSC',],
            ['vessel' => 'FENG HUANG SONG', 'shippingLine' =>  'COSCO',],
            ['vessel' => 'MANOLIS P', 'shippingLine' =>  'MSC',],
            ['vessel' => 'DENIZHAN BAYRAKTAR', 'shippingLine' =>  'BOLLUDA',],
            ['vessel' => 'MSC CAROLINA', 'shippingLine' =>  'MSC',],
            ['vessel' => 'NOTHERN DEBONAIR', 'shippingLine' =>  'MSC',],
            ['vessel' => 'PANTHERA J', 'shippingLine' =>  'ARKON SHIPPING',],
            ['vessel' => 'INGA A', 'shippingLine' =>  'ARKAS LINES',],
            ['vessel' => 'CMA CGM LAPIS', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'MSC JEMIMA', 'shippingLine' =>  'MSC',],
            ['vessel' => 'CMA CGM PLATON', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'CMA CGM HOMERE', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'LUTETIA', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'KARSNES', 'shippingLine' =>  'KLIP MARINE',],
            ['vessel' => 'ARICA', 'shippingLine' =>  'HAPAG-LLOYD',],
            ['vessel' => 'NORTHERN DECISION', 'shippingLine' =>  'MSC',],
            ['vessel' => 'CHOPIN', 'shippingLine' =>  'MARGUISA',],
            ['vessel' => 'MARTHA SCHULTE', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'LOUIS S', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'PORT GDYNIA', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'LILLY SCHULTE', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'CMA CGM ARISTOTE', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'VIKING MERLIN', 'shippingLine' =>  'HAPAG-LLOYD',],
            ['vessel' => 'LETO', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'E.R. FRANCE', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MAPLE LEA', 'shippingLine' =>  'THORCO SHIPPING',],
            ['vessel' => 'BREADBOX  FALCON', 'shippingLine' =>  'BREADBOX SHIPPING LINES',],
            ['vessel' => 'YM ANTWERP', 'shippingLine' =>  'MSC',],
            ['vessel' => 'COSTA RICA STAR', 'shippingLine' =>  'AFRICA EXPRESS LINE',],
            ['vessel' => 'ATLANTIC WEST', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'ATLANTIC DAWN', 'shippingLine' =>  'BALTIC SHIPPING',],
            ['vessel' => 'MV TUNGOR', 'shippingLine' =>  'SEACO',],
            ['vessel' => 'POCAHONTAS', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'MSC COBALTO', 'shippingLine' =>  'MSC',],
            ['vessel' => 'ATLANTIC DISCOVERER', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'NEONILA', 'shippingLine' =>  'BOLLUDA',],
            ['vessel' => 'LEADER CANAKKALE', 'shippingLine' =>  'MILLER AND FLAMA SHIPPING',],
            ['vessel' => 'MSC MADRID', 'shippingLine' =>  'MSC',],
            ['vessel' => 'MSC JANIS 3', 'shippingLine' =>  'MSC',],
            ['vessel' => 'NORDMAPLE', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'EM ATHENS', 'shippingLine' =>  'CMA/DELMAS',],
            ['vessel' => 'OKEE ANN MARI', 'shippingLine' =>  'HAPAG-LLOYD',],
            ['vessel' => 'CS SETUBAL', 'shippingLine' =>  'MSC',],
            ['vessel' => 'THORCO RIO', 'shippingLine' =>  'THORCO SHIPPING',],
            ['vessel' => 'AS SELINA', 'shippingLine' =>  'HAPAG-LLOYD',],
            ['vessel' => 'HANSA ASIA', 'shippingLine' =>  'MSC',],
            ['vessel' => 'HOEGH TARGET', 'shippingLine' =>  'HOEGH AUTOLINERS',],

        ];

        foreach ($vessels as $vessel) {
            $shippingLine = Shipping::select('id')->where('name', '=', $vessel['shippingLine'])->get();

            if (!empty($shippingLine[0])) {
                echo $vessel['vessel'] . ', [' . $shippingLine[0]->id . ']';
            }

        }

        return view('gainde.index');
    }

    /**
     * Save file to database.
     *
     * @param Request $request
     * @return Response
     */
    public function import(Request $request)
    {
        $request->validate(['gainde_file' => 'required|max:5100']);

        $file = Storage::putFile('manifiste', $request->file('gainde_file'));

        // Get file from Storage
        $fileToRead = Storage::get($file);
        $fileContent = json_decode($fileToRead, true);

        foreach ($fileContent as $bls) {
            // highlight_string(json_encode($bls, JSON_PRETTY_PRINT));

            // Check if the destination is Senegal or Mali
            if (strtoupper($bls['pays_dest']) === 'SN' || strtoupper($bls['pays_dest']) === 'ML') {

                // Check if the bl has containers
                if(!empty($bls['conteneurs'])) {

                    $blCode = $this->isAplha($this->getContainerLastChar($bls['num_bl'])) ? $this->getContainerWithoutLastChar($bls['num_bl']) : $bls['num_bl'];

                    $bltype = $this->getBlType($bls['conteneurs'][0]);

                    $twenty_feets_number = $this->get20s($bls['conteneurs']);

                    $fourty_feets_number = $this->get40s($bls['conteneurs']);

                    $twenty_feets_code = $this->get20sContainers($bls['conteneurs']);

                    $fourty_feets_code = $this->get40sContainers($bls['conteneurs']);

                    $found = Vesselle::find($blCode) ? true : false;

                    if(!$found) {

                    }

                }

            }
        }

        return view('gainde.index');
    }

    /**
     * Get bl type through first container.
     *
     * @param Array $firstContainer
     * @return Bltype
     */
    public function getBlType($firstContainer)
    {
        return strtolower(substr($firstContainer[3], 0, 2)) === 're' ? 'REEFER' : 'DRY'  ;
    }

    /**
     * Get number of 20 feet containers.
     *
     * @param Array $blContainers
     * @return Number
     */
    public function get20s($blContainers)
    {
        $n_20 = 0;

        foreach ($blContainers as $container) {
            if (substr($container[2], 0, 2) === '20') {
                $n_20++;
            }
        }

        return $n_20;
    }

    /**
     * Get number of 40 feet containers.
     *
     * @param Array $blContainers
     * @return Number
     */
    public function get40s($blContainers)
    {
        $n_40 = 0;

        foreach ($blContainers as $container) {
            if (substr($container[2], 0, 2) !== '40') {
                $n_40++;
            }
        }

        return $n_40;
    }

    /**
     * Get the concatenated of 20 feet containers' id.
     *
     * @param Array $blContainers
     * @return String
     */
    public function get20sContainers($blContainers)
    {
        $n_20 = 0;

        foreach ($blContainers as $container) {
            if (substr($container[2], 0, 2) === '20') {
                $n_20 .= trim($container[0]) . ' | ';
            }
        }

        return $n_20;
    }

    /**
     * Get the concatenated of 40 feet containers' id.
     *
     * @param Array $blContainers
     * @return String
     */
    public function get40sContainers($blContainers)
    {
        $c_40 = "";

        foreach ($blContainers as $container) {
            if (substr($container[2], 0, 2) !== '40') {
                $c_40 .= trim($container[0]) . ' | ';
            }
        }

        return $c_40;
    }

    /** */
    public function getContainerLastChar($container)
    {
        return substr($container, -1);
    }

    /** */
    public function isAplha($string)
    {
        return ctype_alpha($string);
    }

    /** */
    public function getContainerWithoutLastChar($container)
    {
        return substr($container, 0, strlen($container) -1);
    }

}
